### ISSUE TITLE
Upload new resource

### ISSUE THREAD

**Issue by rosiber** [eawag-rdm/eawag-ckan#12]
Hi, I have tried to upload a zipfile (from a shapefile) with a size of 61 MB. After some minutes the upload prozess stopped without finishing.

**Comment by hvwaldow** [comment]
Tried to upload 512 MB file. Nginx responds "413 Request Entity Too Large". Fixing Nginx config issue now.

**Comment by hvwaldow** [comment]
After also setting CKAN's `ckan.max`_resource_size to 5GB I uploaded a 512 MB file without problem (http://eaw-ckan-dev1.eawag.wroot.emp-eaw.ch/dataset/large-file).

Care to check again, Rosi?

**Comment by hvwaldow** [comment]
For a 4 GB file, Nginx gives me a 504 Gateway Time-out. Getting back to that tomorrow.

**Comment by hvwaldow** [comment]
Ignoring the timeout file upload anyway.
