### ISSUE TITLE
Reorder resources is confusing

### ISSUE THREAD

**Issue by scheidan** [eawag-rdm/eawag-ckan#25]
Another detail:
Trying to reorder the resources i clicked on the little icon with the 4 arrows. This moves the items, but does not reorder them. (clicking on the file names works).

**Comment by hvwaldow** [comment]
Thanks, I see. But that's a usability-detail inside some library used by CKAN core ("Font Awesome / Twitter Bootstrap"). I try to touch those things only in the really worst of bad "not usable like that" - cases.

**Comment by scheidan** [comment]
makes sense
